---
- name: SENDING EMAIL USING GMAIL
  hosts: localhost
  gather_facts: false
  vars_files:
    vars/smtp_secrets.yml
  vars:
    email_smtp_server: 'smtp.gmail.com'
    email_smtp_server_port: '587'
    email_smtp_from_address: 'ansible@lab.local (Ansible)'
    email_smtp_to_address: "{{ email_addresses }}"
    email_report_body: "{{ email_body }}"
    email_smtp_subject: "{{ email_subject }}"
    report_file_name: "{{ email_attachment }}"
  tasks:
    - name: Email with Attachment
      mail:
        host: "{{ email_smtp_server }}"
        port: "{{ email_smtp_server_port }}"
        secure: try
        from: "{{ email_smtp_from_address }}"
        to: "{{ email_smtp_to_address }}"
        subject: "{{ email_smtp_subject }}"
        body: "{{ email_report_body }}"
        attach:
          - "{{ report_file_name }}"
        username: "{{ email_smtp_username }}"
        password: "{{ email_smtp_password }}"
      when: report_file_name != ""
      
    - name: Email without Attachment
      mail:
        host: "{{ email_smtp_server }}"
        port: "{{ email_smtp_server_port }}"
        secure: try
        from: "{{ email_smtp_from_address }}"
        to: "{{ email_smtp_to_address }}"
        subject: "{{ email_smtp_subject }}"
        body: "{{ email_report_body }}"
        username: "{{ email_smtp_username }}"
        password: "{{ email_smtp_password }}"
      when: report_file_name == ""
