---
- name: windows_firewall_playbook.yaml
  hosts: "{{ host_names }}"
  tasks:
    - name: isolating windows host from network
      win_firewall_rule:
        name: Blocking all incoming traffic
        direction: out
        action: block
        protocol: any
        enabled: yes
        state: present
